import React, { useState } from 'react';
import { X, ShieldCheck, Laptop, AlertCircle } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { api, getDefaultServerUrl } from '../../services/api';

export const PairingModal: React.FC = () => {
  const { isPairingModalOpen, setIsPairingModalOpen, pair } = useApp();
  const [serverUrl, setServerUrl] = useState<string>(getDefaultServerUrl());
  const [code, setCode] = useState<string>('');
  const [deviceName, setDeviceName] = useState<string>('My Mobile Phone');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  if (!isPairingModalOpen) return null;

  const handlePair = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!code.trim()) {
      setError('Please enter the 6-digit pairing code');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      api.updateBaseUrl(serverUrl);
      const cleanCode = code.replace(/\D/g, '');
      const ok = await pair(cleanCode, deviceName);
      if (!ok) {
        setError('Pairing failed. Make sure the code is correct and not expired.');
      }
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Cannot connect to Windows Agent. Verify IP and Port.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fadeIn">
      <div className="w-full max-w-md rounded-3xl bg-dark-900 border border-dark-700 shadow-2xl p-6 text-slate-100">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-brand-primary/10 text-brand-primary border border-brand-primary/20">
              <Laptop className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold tracking-tight">Pair with Windows PC</h2>
              <p className="text-xs text-slate-400">Establish secure authenticated connection</p>
            </div>
          </div>
          <button
            onClick={() => setIsPairingModalOpen(false)}
            className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-dark-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handlePair} className="mt-6 space-y-4">
          {error && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-xs">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">
              Windows Agent Host URL
            </label>
            <input
              type="text"
              value={serverUrl}
              onChange={(e) => setServerUrl(e.target.value)}
              placeholder="http://192.168.1.50:8765"
              className="w-full px-3.5 py-2.5 rounded-xl bg-dark-950 border border-dark-700 text-sm font-mono text-slate-200 focus:outline-none focus:border-brand-primary transition-colors"
              required
            />
            <p className="mt-1 text-[11px] text-slate-500">
              Use LAN Wi-Fi IP, Hotspot gateway, or Tailscale (100.x.y.z)
            </p>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">
              6-Digit Pairing PIN
            </label>
            <input
              type="text"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
              placeholder="••••••"
              className="w-full px-3.5 py-3 text-center tracking-[0.6em] text-2xl font-mono font-bold rounded-xl bg-dark-950 border border-dark-700 text-brand-primary focus:outline-none focus:border-brand-primary transition-colors"
              required
            />
            <p className="mt-1.5 text-[11px] text-slate-400">
              Generated by the RCPC Agent running in your Windows terminal.
            </p>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-1.5">
              This Device Name
            </label>
            <input
              type="text"
              value={deviceName}
              onChange={(e) => setDeviceName(e.target.value)}
              className="w-full px-3.5 py-2.5 rounded-xl bg-dark-950 border border-dark-700 text-sm text-slate-200 focus:outline-none focus:border-brand-primary transition-colors"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full mt-2 flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-brand-primary text-dark-950 font-bold text-sm hover:bg-cyan-400 active:scale-[0.98] transition-all shadow-lg shadow-brand-primary/20 disabled:opacity-50"
          >
            {loading ? (
              <div className="w-5 h-5 border-2 border-dark-950 border-t-transparent rounded-full animate-spin" />
            ) : (
              <>
                <ShieldCheck className="w-4 h-4" />
                Pair & Trust Device
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
